// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: events-upcoming.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpcomingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid       int32      `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Timestart    *Timestamp `protobuf:"bytes,3,opt,name=timestart,proto3" json:"timestart,omitempty"` // due date
	Activityname string     `protobuf:"bytes,4,opt,name=activityname,proto3" json:"activityname,omitempty"`
	Course       *Course    `protobuf:"bytes,5,opt,name=course,proto3" json:"course,omitempty"`
}

func (x *UpcomingEvent) Reset() {
	*x = UpcomingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_upcoming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpcomingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingEvent) ProtoMessage() {}

func (x *UpcomingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_upcoming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingEvent.ProtoReflect.Descriptor instead.
func (*UpcomingEvent) Descriptor() ([]byte, []int) {
	return file_events_upcoming_proto_rawDescGZIP(), []int{0}
}

func (x *UpcomingEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpcomingEvent) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UpcomingEvent) GetTimestart() *Timestamp {
	if x != nil {
		return x.Timestart
	}
	return nil
}

func (x *UpcomingEvent) GetActivityname() string {
	if x != nil {
		return x.Activityname
	}
	return ""
}

func (x *UpcomingEvent) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type UpcomingEventList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*UpcomingEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *UpcomingEventList) Reset() {
	*x = UpcomingEventList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_upcoming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpcomingEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcomingEventList) ProtoMessage() {}

func (x *UpcomingEventList) ProtoReflect() protoreflect.Message {
	mi := &file_events_upcoming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcomingEventList.ProtoReflect.Descriptor instead.
func (*UpcomingEventList) Descriptor() ([]byte, []int) {
	return file_events_upcoming_proto_rawDescGZIP(), []int{1}
}

func (x *UpcomingEventList) GetEvents() []*UpcomingEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_events_upcoming_proto protoreflect.FileDescriptor

var file_events_upcoming_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2d, 0x75, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x63, 0x6f, 0x6d,
	0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64,
	0x12, 0x28, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x22,
	0x3b, 0x0a, 0x11, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x55, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x46, 0x0a, 0x21,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x6f, 0x6f, 0x64, 0x6c,
	0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f,
	0x6f, 0x64, 0x6c, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_upcoming_proto_rawDescOnce sync.Once
	file_events_upcoming_proto_rawDescData = file_events_upcoming_proto_rawDesc
)

func file_events_upcoming_proto_rawDescGZIP() []byte {
	file_events_upcoming_proto_rawDescOnce.Do(func() {
		file_events_upcoming_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_upcoming_proto_rawDescData)
	})
	return file_events_upcoming_proto_rawDescData
}

var file_events_upcoming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_upcoming_proto_goTypes = []interface{}{
	(*UpcomingEvent)(nil),     // 0: UpcomingEvent
	(*UpcomingEventList)(nil), // 1: UpcomingEventList
	(*Timestamp)(nil),         // 2: Timestamp
	(*Course)(nil),            // 3: Course
}
var file_events_upcoming_proto_depIdxs = []int32{
	2, // 0: UpcomingEvent.timestart:type_name -> Timestamp
	3, // 1: UpcomingEvent.course:type_name -> Course
	0, // 2: UpcomingEventList.events:type_name -> UpcomingEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_upcoming_proto_init() }
func file_events_upcoming_proto_init() {
	if File_events_upcoming_proto != nil {
		return
	}
	file_timestamp_proto_init()
	file_course_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_events_upcoming_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpcomingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_upcoming_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpcomingEventList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_upcoming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_upcoming_proto_goTypes,
		DependencyIndexes: file_events_upcoming_proto_depIdxs,
		MessageInfos:      file_events_upcoming_proto_msgTypes,
	}.Build()
	File_events_upcoming_proto = out.File
	file_events_upcoming_proto_rawDesc = nil
	file_events_upcoming_proto_goTypes = nil
	file_events_upcoming_proto_depIdxs = nil
}
